# nginx proxy address - http://172.17.0.1:59088

name: tududi
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: chrisvel/tududi:latest
    container_name: tududi-app
    hostname: tududi
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      - TUDUDI_INTERNAL_SSL_ENABLED=false
      - TUDUDI_USER_PASSWORD=${APP_USER_PASS:-password}
      - TUDUDI_USER_EMAIL=${APP_USER_NAME:-admin}@${BASE_DOMAIN_NAME:-example.com}
      - TUDUDI_SESSION_SECRET=${APP_SECRET_TOKEN_32:-0B1Xo65hlCWCDeV9XjSilSSn4JbbXAyo}
    ports:
      - '172.17.0.1:59088:9292'
    volumes:
      - './rootfs/data/tududi:/usr/src/app/tududi_db'
    networks:
      - tududi

networks:
  tududi:
    name: tududi
    external: false
